version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgre
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DATABASE=postgres
    ports:
      - 5432:5432
    restart: always
  app:
    container_name: app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
  redis:
    image: redis
    ports:
      - 6379:6379
    


